package com.example.fixbid.data.repository

import com.example.fixbid.data.remote.dto.VideoCallDto
import com.example.fixbid.data.remote.supabase.Tables
import com.example.fixbid.data.remote.supabase.liveFlow
import com.example.fixbid.domain.model.CallStatus
import com.example.fixbid.domain.model.Resource
import com.example.fixbid.domain.model.VideoCall
import com.example.fixbid.domain.repository.CallRepository
import io.github.jan.supabase.SupabaseClient
import io.github.jan.supabase.postgrest.postgrest
import io.github.jan.supabase.postgrest.query.Columns
import io.github.jan.supabase.postgrest.query.filter.FilterOperator
import io.github.jan.supabase.realtime.PostgresAction
import io.github.jan.supabase.realtime.channel
import io.github.jan.supabase.realtime.decodeRecord
import io.github.jan.supabase.realtime.postgresChangeFlow
import io.github.jan.supabase.realtime.realtime
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.map
import kotlinx.coroutines.flow.merge
import kotlinx.serialization.json.buildJsonObject
import kotlinx.serialization.json.put
import javax.inject.Inject

/**
 * CRUD + realtime for `public.video_calls`.
 *
 * Status transitions are stored as text (`ringing`/`accepted`/...) so the
 * SQL constraint stays human-readable. We always go through this layer
 * instead of letting screens hit Supabase directly so the UI never sees a
 * stale status.
 */
class CallRepositoryImpl @Inject constructor(
    private val client: SupabaseClient
) : CallRepository {

    override suspend fun startCall(
        conversationId: String,
        callerId: String,
        calleeId: String
    ): Resource<VideoCall> = runCatching {
        val now = java.time.Instant.now().toString()
        val dto = VideoCallDto(
            // id is generated by Postgres default; passing empty string makes
            // the serializer omit it via the explicitNulls=false config.
            id = "",
            conversationId = conversationId,
            callerId = callerId,
            calleeId = calleeId,
            status = CallStatus.RINGING.dbValue,
            startedAt = now
        )
        val inserted = client.postgrest[Tables.VIDEO_CALLS]
            .insert(dto) { select(Columns.ALL) }
            .decodeSingle<VideoCallDto>()
        Resource.Success(inserted.toDomain())
    }.getOrElse { Resource.Error(it.message ?: "Không khởi tạo được cuộc gọi") }

    override suspend fun acceptCall(callId: String): Resource<VideoCall> = runCatching {
        val now = java.time.Instant.now().toString()
        val updated = client.postgrest[Tables.VIDEO_CALLS].update(
            buildJsonObject {
                put("status", CallStatus.ACCEPTED.dbValue)
                put("answered_at", now)
            }
        ) {
            filter { eq("id", callId) }
            select(Columns.ALL)
        }.decodeSingle<VideoCallDto>()
        Resource.Success(updated.toDomain())
    }.getOrElse { Resource.Error(it.message ?: "Không thể chấp nhận cuộc gọi") }

    override suspend fun rejectCall(callId: String): Resource<VideoCall> = runCatching {
        val now = java.time.Instant.now().toString()
        val updated = client.postgrest[Tables.VIDEO_CALLS].update(
            buildJsonObject {
                put("status", CallStatus.REJECTED.dbValue)
                put("ended_at", now)
            }
        ) {
            filter { eq("id", callId) }
            select(Columns.ALL)
        }.decodeSingle<VideoCallDto>()
        Resource.Success(updated.toDomain())
    }.getOrElse { Resource.Error(it.message ?: "Không thể từ chối cuộc gọi") }

    override suspend fun endCall(callId: String, durationSeconds: Int): Resource<VideoCall> =
        runCatching {
            val now = java.time.Instant.now().toString()
            val updated = client.postgrest[Tables.VIDEO_CALLS].update(
                buildJsonObject {
                    put("status", CallStatus.ENDED.dbValue)
                    put("ended_at", now)
                    put("duration_seconds", durationSeconds.coerceAtLeast(0))
                }
            ) {
                filter { eq("id", callId) }
                select(Columns.ALL)
            }.decodeSingle<VideoCallDto>()
            Resource.Success(updated.toDomain())
        }.getOrElse { Resource.Error(it.message ?: "Không kết thúc được cuộc gọi") }

    override suspend fun getCall(callId: String): Resource<VideoCall> = runCatching {
        val row = client.postgrest[Tables.VIDEO_CALLS]
            .select(Columns.ALL) { filter { eq("id", callId) } }
            .decodeSingle<VideoCallDto>()
        Resource.Success(row.toDomain())
    }.getOrElse { Resource.Error(it.message ?: "Không tìm thấy cuộc gọi") }

    override fun observeCall(callId: String): Flow<VideoCall?> {
        val channel = client.realtime.channel("video_call_$callId")
        // Both INSERT and UPDATE matter: INSERT covers the rare race when the
        // screen subscribes before the row is fully committed, UPDATE covers
        // every status transition after that.
        val updates = channel.postgresChangeFlow<PostgresAction.Update>(schema = "public") {
            table = Tables.VIDEO_CALLS
            filter("id", FilterOperator.EQ, callId)
        }.map { it.decodeRecordOrNull() }
        val inserts = channel.postgresChangeFlow<PostgresAction.Insert>(schema = "public") {
            table = Tables.VIDEO_CALLS
            filter("id", FilterOperator.EQ, callId)
        }.map { it.decodeRecordOrNull() }
        return channel.liveFlow(merge(updates, inserts))
    }

    override fun observeIncomingCalls(userId: String): Flow<VideoCall> {
        val channel = client.realtime.channel("incoming_calls_$userId")
        // Only INSERTs: a call becomes "incoming" the moment its row appears
        // with this user as callee. Status changes after that are picked up
        // by the per-call observer used inside the call screen.
        val inserts = channel.postgresChangeFlow<PostgresAction.Insert>(schema = "public") {
            table = Tables.VIDEO_CALLS
            filter("callee_id", FilterOperator.EQ, userId)
        }.map { action ->
            runCatching { action.decodeRecord<VideoCallDto>().toDomain() }.getOrNull()
        }
        return channel.liveFlow(
            inserts
                // Drop nulls (decode failure) and stale rows that aren't
                // actually ringing — INSERT events should always be ringing
                // but defence-in-depth: a re-subscription on app restart can
                // replay older rows.
                .let { flow ->
                    kotlinx.coroutines.flow.flow {
                        flow.collect { call ->
                            if (call != null && call.status == CallStatus.RINGING) emit(call)
                        }
                    }
                }
        )
    }

    private fun PostgresAction.Update.decodeRecordOrNull(): VideoCall? =
        runCatching { decodeRecord<VideoCallDto>().toDomain() }.getOrNull()

    private fun PostgresAction.Insert.decodeRecordOrNull(): VideoCall? =
        runCatching { decodeRecord<VideoCallDto>().toDomain() }.getOrNull()
}
